### ISSUE TITLE
Cloudformation create template error

### ISSUE THREAD

**Issue by rushi216** [Sitefinity/SitefinityAWS#1]
While creating new cloudformation stack it is giving below error in singapore region

CREATE_FAILED AWS::EC2::Instance SfBasicWebServer1 API: ec2:RunInstances Not authorized for images: [ami-b25e42d3]

It must be issue related to older windows server 2012 rtm amis, should update it to newer windows server 2012 r2 amis (https://aws.amazon.com/marketplace/fulfillment?productId=0be26530-fe62-4f93-91d1-96c810c19d42)

**Comment by ramifetyani** [comment]
It also gives me an error while creating a new cloudformation 

Error
Template validation error: Parameter 'SourceCidrForRDP' must match pattern ^([0-9]+\.){3}[0-9]+\/[0-9]+$

Any ideas on how to tackle this?

**Comment by nikydobrev** [comment]
Updated ami ids to newer windows server 2012 r2, issue with "...Not authorized for images: [ami-b25e42d3]" is now resolved.
